name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          $vsInstallerUrl = "https://aka.ms/vs/17/release/vs_BuildTools.exe"
          $vsInstallerPath = "$env:RUNNER_TEMP\vs_BuildTools.exe"
          $installDir = "C:\MyVS"

          Invoke-WebRequest $vsInstallerUrl -OutFile $vsInstallerPath

          Start-Process -Wait -FilePath $vsInstallerPath -ArgumentList `
            "--installPath `"$installDir`"", `
            "--add Microsoft.VisualStudio.Workload.VCTools", `
            "--includeRecommended", `
            "--passive", "--norestart", "--wait"

      - name: Setup MSVC Environment
        shell: cmd
        run: |
          call "C:\MyVS\VC\Auxiliary\Build\vcvars64.bat"

      - name: Build
        shell: cmd
        run: |
          call "C:\MyVS\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022"
          cmake --build . --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: DLL
          path: D:\a\PvZ-GW-Map-Loader\PvZ-GW-Map-Loader\build\Release\
